version: '2'
services:
    prestigemicroservice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/PrestigeMicroservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=PrestigeMicroservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
